'use client'

import { useEffect, useState } from 'react'

type Tenant={id:string;name:string;slug:string;createdAt:string;workspaces:{id:string;name:string;slug:string}[];memberships:{id:string;role:string;user:{id:string;name:string|null;email:string}}[];subscriptions:{id:string;status:string;billingInterval:string;currentPeriodEnd:string;plan:{name:string;monthlyPrice:number;yearlyPrice:number;currency:string}}[]}

export default function TenantDetail({params}:{params:Promise<{id:string}>}){
 const [tenant,setTenant]=useState<Tenant|null>(null); const [error,setError]=useState('')
 useEffect(()=>{params.then(({id})=>fetch(`/api/admin/tenants/${id}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setTenant(d.tenant)}).catch(e=>setError(e.message)))},[params])
 if(error)return <main className="min-h-screen bg-slate-950 p-8 text-red-300">{error}</main>
 if(!tenant)return <main className="min-h-screen bg-slate-950 p-8 text-slate-500">Loading tenant…</main>
 const sub=tenant.subscriptions[0]
 return <main className="min-h-screen bg-slate-950 p-6 text-slate-100 md:p-10"><div className="mx-auto max-w-6xl"><a href="/tenants" className="text-sm text-slate-500">← Tenants</a><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">{tenant.name}</h1><p className="mt-1 text-slate-500">{tenant.slug}</p></div><span className="rounded-full bg-slate-800 px-3 py-1 text-sm">{sub?.status??'No subscription'}</span></div><div className="mt-8 grid gap-5 md:grid-cols-3"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><p className="text-sm text-slate-500">Plan</p><p className="mt-2 text-2xl font-semibold">{sub?.plan.name??'—'}</p><p className="mt-2 text-sm text-slate-400">{sub?`${sub.plan.currency} ${sub.billingInterval==='YEARLY'?sub.plan.yearlyPrice:sub.plan.monthlyPrice} / ${sub.billingInterval.toLowerCase()}`:'—'}</p></section><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><p className="text-sm text-slate-500">Users</p><p className="mt-2 text-2xl font-semibold">{tenant.memberships.length}</p></section><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><p className="text-sm text-slate-500">Workspaces</p><p className="mt-2 text-2xl font-semibold">{tenant.workspaces.length}</p></section></div><div className="mt-8 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="font-semibold">Team</h2><div className="mt-4 space-y-3">{tenant.memberships.map(m=><div key={m.id} className="flex justify-between border-b border-slate-800 pb-3"><div><p>{m.user.name||m.user.email}</p><p className="text-sm text-slate-500">{m.user.email}</p></div><span className="text-sm text-slate-400">{m.role}</span></div>)}</div></section><section className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="font-semibold">Workspaces</h2><div className="mt-4 space-y-3">{tenant.workspaces.map(w=><div key={w.id} className="flex justify-between border-b border-slate-800 pb-3"><p>{w.name}</p><span className="text-sm text-slate-500">{w.slug}</span></div>)}</div></section></div><section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="font-semibold">Subscription</h2><p className="mt-3 text-sm text-slate-400">{sub?`Current period ends ${new Date(sub.currentPeriodEnd).toLocaleDateString()}`:'No subscription record.'}</p></section></div></main>
}
