'use client'

import { useEffect, useState } from 'react'

type Insight={priority:string;type:string;title:string;detail:string}
type Data={metrics:{tenants:number;activeSubscriptions:number};pendingWork:Insight[];comparison:{note:string}}
type Answer={answer:string;data:{pastDue:number;expiringTrials:number;revenue:number;expenses:number;refunds:number;profit:number}}

export default function AiPage(){
 const [data,setData]=useState<Data|null>(null); const [question,setQuestion]=useState(''); const [answer,setAnswer]=useState<Answer|null>(null); const [asking,setAsking]=useState(false)
 useEffect(()=>{fetch('/api/admin/ai').then(r=>r.json()).then(setData)},[])
 async function ask(){if(!question.trim())return;setAsking(true);try{const r=await fetch('/api/admin/ai/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});setAnswer(await r.json())}finally{setAsking(false)}}
 return <main className="min-h-screen bg-slate-950 p-6 text-slate-100 md:p-10"><div className="mx-auto max-w-6xl"><div><p className="text-sm text-slate-500">Briqona Control Center</p><h1 className="mt-1 text-3xl font-semibold">AI Business Copilot</h1><p className="mt-2 text-slate-400">Ask the platform what needs attention and get a data-backed operational summary.</p></div><div className="mt-8 rounded-2xl border border-slate-800 bg-slate-900 p-6"><div className="flex gap-3"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')ask()}} placeholder="e.g. Pending work kya hai?" className="flex-1 rounded-lg border border-slate-700 bg-slate-950 px-4 py-3 outline-none"/><button onClick={ask} disabled={asking} className="rounded-lg bg-white px-5 font-medium text-slate-950 disabled:opacity-50">{asking?'Thinking…':'Ask AI'}</button></div>{answer&&<div className="mt-5 rounded-xl border border-slate-800 bg-slate-950 p-5"><p className="font-medium">🤖 {answer.answer}</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><div>Past due <b>{answer.data.pastDue}</b></div><div>Trials <b>{answer.data.expiringTrials}</b></div><div>Revenue <b>{answer.data.revenue}</b></div><div>Profit <b>{answer.data.profit}</b></div></div></div>}</div>{!data?<p className="mt-8 text-slate-500">Analyzing platform…</p>:<><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-sm text-slate-500">Tenants</p><p className="mt-2 text-2xl font-semibold">{data.metrics.tenants}</p></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-sm text-slate-500">Active subscriptions</p><p className="mt-2 text-2xl font-semibold">{data.metrics.activeSubscriptions}</p></div></div><section className="mt-8 rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="font-semibold">⚡ Pending work</h2><div className="mt-4 space-y-3">{data.pendingWork.length?data.pendingWork.map((x,i)=><div key={i} className="rounded-xl border border-slate-800 p-4"><div className="flex justify-between gap-3"><p>{x.title}</p><span className="text-xs text-slate-500">{x.priority}</span></div><p className="mt-1 text-sm text-slate-500">{x.detail}</p></div>):<p className="text-sm text-slate-500">No payment or trial alerts found.</p>}</div></section><section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900 p-6"><h2 className="font-semibold">📊 Yesterday → Today</h2><p className="mt-3 text-sm text-slate-400">{data.comparison.note}</p></section></>}</div></main>
}
